import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import CNavigation from "./components/CNavigation";
import { Providers } from "@/lib/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <CNavigation />
          <main className="flex justify-center bg-sky-100">
            <div className="container mx-auto py-5">{children}</div>
          </main>
        </Providers>
      </body>
    </html>
  );
}
