/* Core */
import { createSlice, type PayloadAction } from "@reduxjs/toolkit";

/* Instruments */
import {
  fetchMarketplacesByYearAndMonthAsync,
  fetchMarketplacesAsync,
} from "./thunks";
import { Marketplace } from "@/app/module";

const initialState: MarketplacesSliceState = {
  allMarketplaces: undefined,
  marketplaceByMonthAndYear: undefined,
  status: "idle",
};

export const marketplacesSlice = createSlice({
  name: "marketplaces",
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    // increment: (state) => {
    //   // Redux Toolkit allows us to write "mutating" logic in reducers. It
    //   // doesn't actually mutate the state because it uses the Immer library,
    //   // which detects changes to a "draft state" and produces a brand new
    //   // immutable state based off those changes
    //   state.value += 1;
    // },
    // decrement: (state) => {
    //   state.value -= 1;
    // },
    // // Use the PayloadAction type to declare the contents of `action.payload`
    // incrementByAmount: (state, action: PayloadAction<number>) => {
    //   state.value += action.payload;
    // },
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
    builder
      .addCase(fetchMarketplacesAsync.pending, (state) => {
        state.status = "loading";
      })
      .addCase(fetchMarketplacesAsync.fulfilled, (state, action) => {
        state.status = "idle";
        state.allMarketplaces = action.payload;
      })
      .addCase(
        fetchMarketplacesByYearAndMonthAsync.fulfilled,
        (state, action) => {
          state.marketplaceByMonthAndYear = action.payload;
        }
      );
  },
});

/* Types */
export interface MarketplacesSliceState {
  allMarketplaces?: Array<Marketplace>;
  marketplaceByMonthAndYear?: Array<Marketplace>;
  status: "idle" | "loading" | "failed";
}
